### ISSUE TITLE
8.0 手机 崩溃，能更新下库么

### ISSUE THREAD

**Issue by Carlxx** [maning0303/ZXingCodeDemo#11]
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

修改下 MNScanCaptureTheme 就可以，不然每次用都 要添加 lib ,哈哈

**Comment by maning0303** [comment]
@Carlxx 不好意思，刚刚看到这个问题。谢谢反馈，明天就会更新下这个问题，谢谢反馈哈。

**Comment by maning0303** [comment]
@Carlxx 你好，新版本已经发布了，修复了这个问题，你可以试试新版本，有什么好的优化建议可以提出来哈，感谢反馈。
