### ISSUE TITLE
相册选择的二维码识别率极低（原因：内存泄漏）

### ISSUE THREAD

**Issue by yedajiang44** [maning0303/ZXingCodeDemo#12]
只要是手机拍摄的二维码，识别率基本为零

**Comment by yedajiang44** [comment]
原因是因为我的图片是手机拍摄的，所以比较大，压缩后再解析就行了
[代码
位置](https://github.com/maning0303/MNZXingCode/blob/89dbd6efc631a9bdada4950348a6bba6cafaad41/libraryzxing/src/main/java/com/google/zxing/client/android/CaptureActivity.java#L219)
可以压缩bitmap或者压缩原图后再转bitmap后使用
如修复请艾特我一下，谢谢~

**Comment by maning0303** [comment]
@yedajiang44 感谢发现的问题，我会尽快修复，然后通知你。

**Comment by maning0303** [comment]
@yedajiang44 问题已经修复了，你看看最新版本V1.1.7，感谢你的反馈。

**Comment by yedajiang44** [comment]
@maning0303 刚才跑了下，依旧无法识别，然后跑过来看了下代码，发现用的是尺寸压缩，尺寸压缩的话有变形风险不说，二维码也会变小，从而影响解析成功率，所以我觉得用质量压缩比较稳妥，我上次测试的时候用的是[鲁班压缩](https://github.com/Curzibn/Luban)，原图4k（尺寸）接近5M（大小），完美解决内存泄漏问题
