### ISSUE TITLE
异常 nly fullscreen opaque activities can request orientation 

### ISSUE THREAD

**Issue by haife** [maning0303/ZXingCodeDemo#14]
版本V2.0.0，三星Galaxy S9  8.0系统还是报错 “nly fullscreen opaque activities can request orientation”
后面修改了libraryzxing中style 样式
<style name="MNScanCaptureTheme" parent="android:Theme.Holo.NoActionBar">
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowAnimationStyle">@style/MNScanAnimation</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowIsTranslucent">false</item>
    </style>

**Comment by maning0303** [comment]
@haife 感谢反馈，我这边尽快发新版本修复这个问题。

**Comment by maning0303** [comment]
@haife 试一下最新版本V2.0.1，修改了Activity的样式；
