### ISSUE TITLE
生成带logo的二维码可否新增仿微信的样式? 

### ISSUE THREAD

**Issue by lydlovezjr** [maning0303/ZXingCodeDemo#18]
1.微信图片是在线图片
2.添加白色边框和灰色边框

**Comment by maning0303** [comment]
@lydlovezjr 这个我下来研究研究，能搞的话尽快安排上。

**Comment by maning0303** [comment]
@lydlovezjr https://github.com/SumiMakito/AwesomeQRCode 这个库看看能不能满足你的需求

**Comment by lydlovezjr** [comment]
感谢大佬,我看看.也希望大佬能研究一下.
添加到库里.
