### ISSUE TITLE
不支持条形码吗？

### ISSUE THREAD

**Issue by ximenchuipaopao** [maning0303/ZXingCodeDemo#19]
不支持条形码吗？
另外最新版本的二维码扫描最低支持的是7.0，7.0以下无法使用

**Comment by maning0303** [comment]
@ximenchuipaopao 条形码是支持的，7.0这个问题确实没有注意，这个我后面把zxing包引用放在外面，需要支持7.0一下的使用zxing 3.3.3，需要支持的可以使用zxing3.4.0以上版本，感谢反馈

**Comment by maning0303** [comment]
@ximenchuipaopao 最新版本支持自己配置zxing版本了，这样可以避免7.0问题，感谢反馈。
