### ISSUE TITLE
你好，请问下怎么设置扫描结果点的点击事件啊，类似微信和支付宝

### ISSUE THREAD

**Issue by jiangwenfei** [maning0303/ZXingCodeDemo#20]

**Comment by maning0303** [comment]
@jiangwenfei 暂时还没有这样的功能，他们那是同一屏幕显示多个二维码有点击事件，这边暂时还不支持这种。后期看看有没有好的方案。

**Comment by maning0303** [comment]
@jiangwenfei 下个版本支持多个一屏多个二维码会出现扫描结果点可点击，类似微信

**Comment by maning0303** [comment]
@jiangwenfei 多个二维码扫码结果可点击最新版本已支持，请查看最新版本Demo,感谢反馈！
