### ISSUE TITLE
支持多条形码吗

### ISSUE THREAD

**Issue by Hiram-Y** [maning0303/ZXingCodeDemo#22]

**Comment by maning0303** [comment]
@Hiram-Y 不支持多条形码，暂时只支持多二维码

**Comment by maning0303** [comment]
@Hiram-Y 另外一个项目MNMLKitScanner支持同时多条形码和多二维码，设置基本上和本项目一模一样。可以尝试一下：https://github.com/maning0303/MNMLKitScanner
