### ISSUE TITLE
要是多二维码同时扫描支持条形码就完美了。。。 难受啊

### ISSUE THREAD

**Issue by 603154899** [maning0303/ZXingCodeDemo#23]

**Comment by maning0303** [comment]
@603154899 是挺难搞的，zxing QRCodeMultiReader支持多二维码但是不支持条形码，MultiFormatReader又只能支持单个的扫描，后面再看看有没有其它解决方案吧，你看看有没有解决方案可以交流下

**Comment by jiqianwen** [comment]
华为的扫码服务或者微信开源的opencv可以试试

**Comment by maning0303** [comment]
@jiqianwen https://github.com/maning0303/MNMLKitScanner  最新一个基于MLKit的扫码识别支持多二维码和多条形码，参数配置基本一样。可以关注一下
