### ISSUE TITLE
扫描结果的中心点位置总是在二维码偏下位置

### ISSUE THREAD

**Issue by jiqianwen** [maning0303/ZXingCodeDemo#25]

**Comment by jiqianwen** [comment]
完全自定义的扫码界面，应该如何控制一个扫描结果直接返回，多个扫描结果选择之后返回？还有那个扫描结果页的取消文字能不能动态隐藏，暴露个API判断当前是否显示了扫描结果的View，给用户自己处理相关逻辑

**Comment by maning0303** [comment]
@jiqianwen 我这边几个测试机都是没有问题的，你可以加一下我微信具体聊一聊什么问题？13237110231

**Comment by maning0303** [comment]
@jiqianwen 最新版本修复这个问题，请使用最新版本，感谢反馈。
