### ISSUE TITLE
怎么修改边框和扫描线的颜色?

### ISSUE THREAD

**Issue by badboy-tian** [maning0303/ZXingCodeDemo#3]

**Comment by maning0303** [comment]
这个暂时不行呢，里面用的图片，你需要修改的话把源码导入，直接改布局就好了！

**Comment by badboy-tian** [comment]
嗯  我以为是用的颜色代码呢  我fork后换了图片

2017-08-03 9:41 GMT+08:00 马宁 <notifications@github.com>:

**Comment by maning0303** [comment]
恩恩，可以自行修改一下，弄得更加方便点！
