### ISSUE TITLE
扫码识别速度很慢

### ISSUE THREAD

**Issue by fairytale110** [maning0303/ZXingCodeDemo#5]
不知道楼主可有优化建议么

**Comment by maning0303** [comment]
@fairytale110 你试试最新的代码，换了zxing最新的版本代码。

**Comment by maning0303** [comment]
@fairytale110   识别区域做了优化，不用二维码放在很远才能识别

**Comment by maning0303** [comment]
@fairytale110  现在我测试的识别速度还是很快的，要是有什么问题再提出来，这个就先关闭了，感谢提的意见
