### ISSUE TITLE
扫描框为什么不是正方形？

### ISSUE THREAD

**Issue by Q773000230** [maning0303/ZXingCodeDemo#7]
在安卓4.1的真机上，打开的扫描框是长方形的，看上去好丑，请问怎么处理成正方形？

**Comment by maning0303** [comment]
@Q773000230  长方形？ 有没有截图？相机内容是拉伸变形的还是只是扫描框是变形的？

**Comment by Q773000230** [comment]
@maning0303

**Comment by Q773000230** [comment]
@maning0303 

![bc224f730fbcab7068243471fef7bd6d](https://user-images.githubusercontent.com/13879884/33699567-e6b6953c-db4e-11e7-8bc1-3c944aae8397.jpg)
